# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings (access via {{ site.var }})
title: minisim
email: matt@incubatory.xyz
description: >- # this means to ignore newlines until "baseurl:"
  minisim - a toy molecular dynamics simulator, for learning and
  experimentation.
baseurl: "/minisim"
url: ""
twitter_username: coffeeandsoju
github_username:  mattfeng

# Build settings
markdown: kramdown
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
